package main

import(
	"fmt"
	"strings"
	"bufio"
	"os"
	"time"
	"github.com/NoeRicklin/pokedex/internal/pokeapi/utils"
)

type cliCommand struct {
	name		string
	desc		string
	callback	func(...string) error
}

type AreaJSON struct {
	Count		int
	Next		string
	Previous	string
	Results		[]struct{
		Name	string
		Url		string
	}
}

type AutoGenerated struct {
	EncounterMethodRates []any
	GameIndex	int
	ID			int
	Location	any
	Name		string
	Names		[]any
	PokemonEncounters []struct {
		Pokemon struct {
			Name string
			URL  string
		}
		VersionDetails []any
	}
}

var commands map[string]cliCommand
var s *bufio.Scanner

func main() {
	commands = map[string]cliCommand{
		"exit": {
			name:		"exit",
			desc:		"Exits the REPL",
			callback:	cmdExit,
		},
		"help": {
			name:		"help",
			desc:		"Displays the help",
			callback:	cmdHelp,
		},
		"map": {
			name:		"map",
			desc:		"Shows next 20 locations",
			callback:	cmdMap,
		},
		"mapb": {
			name:		"mapb",
			desc:		"Shows prev 20 locations",
			callback:	cmdMapb,
		},
		"explore": {
			name:		"explore",
			desc:		"Shows Pokémon in area",
			callback:	cmdExplore,
		},
	}

	s = bufio.NewScanner(os.Stdin)
	utils.SetupCache(3 * time.Second)

	var input string

	for {
		fmt.Print("Pokedex >")
		s.Scan()
		
		input = s.Text()
		cmds := cleanInput(input)

		if _, ok := commands[cmds[0]]; !ok {
			fmt.Println("Unknown Command")
			continue
		}

		if err := commands[cmds[0]].callback(cmds[1:]...); err != nil {
			fmt.Println(err)
		}
	}
}

func cleanInput(text string) []string {
	trimmed := strings.Trim(text, " ")

	words := strings.Split(trimmed, " ")

	var lowerWords []string
	for _, word := range words {
		lowerWords = append(lowerWords, strings.ToLower(word))
	}

	return lowerWords
}

func cmdExit(argv ...string) error {
	fmt.Println("Closing the Pokedex... Goodbye!")
	os.Exit(0)
	return nil
}

func cmdHelp(argv ...string) error {
	fmt.Print("Welcome to the Pokedex!\nUsage:\n\n")

	for cmd, _ := range commands {
		fmt.Printf("%s: %s\n", commands[cmd].name, commands[cmd].desc)
	}
	return nil
}

var count int
func cmdMap(argv ...string) error {
	url := fmt.Sprintf("https://pokeapi.co/api/v2/location-area/?limit=20&offset=%d",
	count * 20)

	area, err := utils.GetURLBody[AreaJSON](url)
	if err != nil { return err }

	for _, location := range area.Results {
		fmt.Println(location.Name)
	}

	count++
	return nil
}

func cmdMapb(argv ...string) error {
	count--		// Cancels out last increase of count
	count--
	if count < 0 {
		return fmt.Errorf("You're on the first page")
	}

	return cmdMap()
}

func cmdExplore(argv ...string) error {
	url := fmt.Sprintf("https://pokeapi.co/api/v2/location-area/%s",
	argv[0])

	area, err := utils.GetURLBody(url)
	if err != nil { return err }

	for _, pokeM
}
